### ISSUE TITLE
Макеты | dev-0

### ISSUE THREAD

**Issue by jEUGENEdev** [coursework-moop-22kbpi1-kubstu/desktop-client#1]
Проработать макеты всех основных окон приложения

**Comment by DP1415** [comment]
![Окно входа](https://github.com/coursework-moop-22kbpi1-kubstu/desktop-client/assets/147081149/46f0845a-57d9-4890-b9e1-d71a82f73a1e)
![Окно главного меню](https://github.com/coursework-moop-22kbpi1-kubstu/desktop-client/assets/147081149/7205bd79-bccf-4a11-aa29-93228d240fe4)
![Окно настроек](https://github.com/coursework-moop-22kbpi1-kubstu/desktop-client/assets/147081149/8a7250d2-3aa6-46e4-9909-b3a61f95993a)
![Окно профиля пользователя](https://github.com/coursework-moop-22kbpi1-kubstu/desktop-client/assets/147081149/550c2072-4adb-425e-b516-bf799901949b)
![Окно регистрации](https://github.com/coursework-moop-22kbpi1-kubstu/desktop-client/assets/147081149/e6bcc427-e530-4a32-a15b-5cf6273bae60)
